/**:
  ros__parameters:
    update_rate: 500

    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    velocity_group_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_group_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7